{
  "openapi": "3.0.0",
  "info": {
    "title": "Application Subscriber API",
    "version": "0.2",
    "description": "API vom Fachverfahren zum Zustelldienst",
    "contact": {
      "name": "FITKO",
      "url": "https://www.fitko.de/"
    },
    "license": {
      "name": "Creative Commons Attribution Share Alike 4.0 (CC BY-SA 4.0)",
      "url": "https://creativecommons.org/licenses/by-sa/4.0/"
    }
  },
  "servers": [
    {
      "url": "https://subscriber.fiep-poc.de",
      "description": "Produktionsumgebung der API."
    },
    {
      "url": "https://xfall-sender-api.sandbox.fiep-poc.de",
      "description": "Testumgebung der API."
    }
  ],
  "paths": {
    "/{subscriber-id}/destinations/{destination-id}/applications/{application-id}/docs/{doc-id}": {
      "get": {
        "summary": "Get Application Document",
        "operationId": "get-application-document",
        "description": "Ruf ein Dokument (Formular oder Anlage) der Application ab.",
        "tags": [
          "Application Retrieval"
        ],
        "security": [
          {
            "Production API Key": [
              "{subscriber-id}:manage",
              "{subscriber-id}:application:receive",
              "{subscriber-id}:destination:{destination-id}:application:receive"
            ]
          },
          {
            "Sandbox API Key": []
          }
        ]
      }
    },
    "/{subscriber-id}/destinations/{destination-id}/applications/{application-id}/data": {
      "get": {
        "summary": "Get Application Data",
        "operationId": "get-application-data",
        "description": "Ruft die Fachdaten der Application ab.\n\nBeispiele:\n#### JSON\n```json\n{\n    \"F99000001\": \"Eins\",\n    \"G99000001\": {\n        \"F99000002\": \"Zwei\",\n        \"F99000003\": \"Drei\"\n    }\n}\n```\n\n#### XML\n```xml\n<S99000001>\n  <F99000001>Eins</F99000001>\n  <G99000001>\n    <F99000002>Zwei</F99000002>\n    <F99000003>Drei</F99000003>\n  </G99000001>\n</S99000001>\n```",
        "tags": [
          "Application Retrieval"
        ],
        "security": [
          {
            "Production API Key": [
              "{subscriber-id}:manage",
              "{subscriber-id}:application:receive",
              "{subscriber-id}:destination:{destination-id}:application:receive"
            ]
          },
          {
            "Sandbox API Key": []
          }
        ]
      }
    },
    "/{subscriber-id}/destinations/{destination-id}/applications/{application-id}": {
      "get": {
        "summary": "Get Application Metadata",
        "operationId": "get-application",
        "description": "Ruft eine wartende Application ab.",
        "tags": [
          "Application Retrieval"
        ],
        "security": [
          {
            "Production API Key": [
              "{subscriber-id}:manage",
              "{subscriber-id}:application:receive",
              "{subscriber-id}:destination:{destination-id}:application:receive"
            ]
          },
          {
            "Sandbox API Key": []
          }
        ]
      },
      "post": {
        "summary": "Acknowledge Application",
        "operationId": "ack-application",
        "description": "Bestätigt die Abholung der Application. Über den Parameter `final-delivery` im Body wird gesteuert, wie der Folgestatus aussieht:\n\n| final-delivery | status      |\n| -------------- | ----------- |\n| `false`        | \"forwarded\" |\n| `true`         | \"delivered\" |\n\nDer Parameter `final-delivery` zeigt an, ob der Antrag noch weitergesendet wird (`false`) oder das finale Ziel erreicht hat (`true`).\n\nSofern der Wert `false` übergeben wurde, muss zu einem späteren [...]",
        "tags": [
          "Application Retrieval"
        ],
        "security": [
          {
            "Production API Key": [
              "{subscriber-id}:manage",
              "{subscriber-id}:application:receive",
              "{subscriber-id}:destination:{destination-id}:application:receive"
            ]
          },
          {
            "Sandbox API Key": []
          }
        ]
      }
    },
    "/{subscriber-id}/destinations/{destination-id}/applications": {
      "get": {
        "summary": "List Applications",
        "operationId": "list-applications",
        "description": "Ruft die Liste der wartenden Applications ab.",
        "tags": [
          "Application Retrieval"
        ],
        "security": [
          {
            "Production API Key": [
              "{subscriber-id}:manage",
              "{subscriber-id}:application:receive",
              "{subscriber-id}:destination:{destination-id}:application:receive"
            ]
          },
          {
            "Sandbox API Key": []
          }
        ]
      }
    },
    "/{subscriber-id}/destinations/{destination-id}": {
      "get": {
        "summary": "Get Destination",
        "operationId": "get-destination",
        "description": "Übertragungsziel abfragen",
        "tags": [
          "Destination Management"
        ],
        "security": [
          {
            "Production API Key": [
              "{subscriber-id}:destination:read",
              "{subscriber-id}:destination:manage",
              "{subscriber-id}:manage",
              "{subscriber-id}:destination:{destination-id}:read"
            ]
          },
          {
            "Sandbox API Key": []
          }
        ]
      },
      "put": {
        "summary": "Update Destination",
        "operationId": "update-destination",
        "description": "Übertragungsziel aktualisieren",
        "tags": [
          "Destination Management"
        ],
        "security": [
          {
            "Production API Key": [
              "{subscriber-id}:manage",
              "{subscriber-id}:destination:update",
              "{subscriber-id}:destination:manage",
              "{subscriber-id}:destination:{destination-id}:update"
            ]
          },
          {
            "Sandbox API Key": []
          }
        ]
      },
      "delete": {
        "summary": "Delete Destination",
        "operationId": "delete-destination",
        "description": "Übertragungsziel löschen",
        "tags": [
          "Destination Management"
        ],
        "security": [
          {
            "Production API Key": [
              "{subscriber-id}:manage",
              "{subscriber-id}:destination:manage",
              "{subscriber-id}:destination:delete",
              "{subscriber-id}:destination:{destination-id}:delete"
            ]
          },
          {
            "Sandbox API Key": []
          }
        ]
      }
    },
    "/{subscriber-id}/destinations": {
      "get": {
        "summary": "List Destinations",
        "operationId": "list-destinations",
        "description": "Ruft die Liste aller Destinations dieses Accounts auf.",
        "tags": [
          "Destination Management"
        ],
        "security": [
          {
            "Production API Key": [
              "{subscriber-id}:destination:read",
              "{subscriber-id}:manage",
              "{subscriber-id}:destination:manage"
            ]
          },
          {
            "Sandbox API Key": []
          }
        ]
      },
      "post": {
        "summary": "Create Destination",
        "operationId": "create-destination",
        "description": "Legt eine neue Destination an.",
        "tags": [
          "Destination Management"
        ],
        "security": [
          {
            "Production API Key": [
              "{subscriber-id}:manage",
              "{subscriber-id}:destination:manage",
              "{subscriber-id}:destination:create"
            ]
          }
        ]
      }
    }
  },
  "tags": [
    {
      "name": "Destination Management"
    },
    {
      "name": "Application Retrieval"
    }
  ],
  "components": {
    "securitySchemes": {
      "Production API Key": {
        "type": "oauth2",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "",
            "refreshUrl": "",
            "scopes": {
              "{subscriber-id}:destination:read": "Dieser Zugriffsbereich erlaubt bei allen Destination-Informationen ein lesender Zugriff.",
              "{subscriber-id}:destination:create": "Der Zugriffsbereich erlaubt Destinations neu anzulegen und zu verändern.",
              "{subscriber-id}:destination:update": "Dieser Zugriffsbereich erlaubt es, bestehende Destinations zu verändern.",
              "{subscriber-id}:destination:manage": "Dieser Zugriffsbereich alle Destination Endpunkte eines Subscriber genutzt werden.",
              "{subscriber-id}:destination:{destination-id}:read": "Mit diesem Zugriffsbereich wird ein lesender Zugriff auf eine spezifische Destination ermöglicht.",
              "{subscriber-id}:destination:{destination-id}:update": "Mit diesem Zugriffsbereich wird ein schreibende Zugriff auf eine spezifische Destination ermöglicht.",
              "{subscriber-id}:application:receive": "Dieser Zugriffsbereich erlaubt es, Anträge für allen Destinations abzuholen.",
              "{subscriber-id}:destination:{destination-id}:application:receive": "Dieser Zugriffsbereich erlaubt es, Anträge einer spezifischen Destination abzuholen.",
              "{subscriber-id}:manage": "Dieser Zugriffsbereich die vollständige Nutzung aller Endpunkte eines Subscribers.",
              "{subscriber-id}:destination:delete": "Dieser Zugriffsbereich erlaubt die Löschung von Destinations eines Accounts.",
              "{subscriber-id}:destination:{destination-id}:delete": "Dieser Zugriffsbereich erlaubt es, eine spezifische Destination zu löschen."
            }
          }
        },
        "description": "Dieses Authentifizierungsmethode wird genutzt, um den Zugriff auf die Produktiv API zu autorisieren. "
      },
      "Sandbox API Key": {
        "name": "API-Key",
        "type": "apiKey",
        "in": "header",
        "description": "Der API-Key wird als Authentifizierungsmittel für die Sandbox API benutzt."
      }
    }
  }
}